# Generated by Django 5.0.8 on 2024-08-25 00:32

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player_id",
                    models.IntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=250)),
                ("last_name", models.CharField(max_length=250)),
                ("full_name", models.CharField(max_length=250)),
                ("search_full_name", models.CharField(max_length=250)),
                ("search_first_name", models.CharField(max_length=250)),
                ("search_last_name", models.CharField(max_length=250)),
                (
                    "team",
                    models.CharField(
                        choices=[
                            ("ARI", "Arizona"),
                            ("ATL", "Atlanta"),
                            ("BAL", "Baltimore"),
                            ("BUF", "Buffalo"),
                            ("CAR", "Carolina"),
                            ("CHI", "Chicago"),
                            ("CIN", "Cincinnati"),
                            ("CLE", "Cleveland"),
                            ("DAL", "Dallas"),
                            ("DEN", "Denver"),
                            ("DET", "Detroit"),
                            ("GB", "Green Bay"),
                            ("HOU", "Houston"),
                            ("IND", "Indianapolis"),
                            ("JAX", "Jacksonville"),
                            ("KC", "Kansas City"),
                            ("LV", "Las Vegas"),
                            ("LAR", "Los Angeles Rams"),
                            ("MIA", "Miami"),
                            ("MIN", "Minnesota"),
                            ("NE", "New England"),
                            ("NO", "New Orleans"),
                            ("NYG", "New York Giants"),
                            ("NYJ", "New York Jets"),
                            ("PHI", "Philadelphia"),
                            ("PIT", "Pittsburgh"),
                            ("SF", "San Francisco"),
                            ("SEA", "Seattle"),
                            ("TB", "Tampa Bay"),
                            ("TEN", "Tennessee"),
                            ("WAS", "Washington"),
                        ],
                        max_length=250,
                    ),
                ),
                ("position", models.CharField(max_length=250)),
                (
                    "fantasy_positions",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("QB", "Quarterback"),
                            ("RB", "Running Back"),
                            ("WR", "Wide Receiver"),
                            ("TE", "Tight End"),
                            ("K", "Kicker"),
                            ("DEF", "Defense"),
                            ("DB", "Defensive Back"),
                            ("LB", "Linebacker"),
                            ("DL", "Defensive Line"),
                            ("OL", "Offensive Line"),
                            ("OG", "Offensive Guard"),
                            ("OT", "Offensive Tackle"),
                            ("LS", "Long Snapper"),
                            ("P", "Punter"),
                        ],
                        max_length=250,
                    ),
                ),
                ("years_exp", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("status", models.CharField(max_length=250)),
                ("number", models.IntegerField(blank=True, null=True)),
                ("depth_chart_position", models.CharField(max_length=250)),
                ("depth_chart_order", models.IntegerField(blank=True, null=True)),
                ("sport", models.CharField(default="nfl", max_length=250)),
                ("search_rank", models.IntegerField(default=9999999)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Injury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_part", models.CharField(max_length=250)),
                ("status", models.CharField(max_length=250)),
                ("notes", models.TextField()),
                ("start_date", models.DateField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injuries",
                        to="sleeper_bot.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitions",
                        to="sleeper_bot.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerIDs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=250)),
                ("fantasy_data_id", models.IntegerField(blank=True, null=True)),
                ("stats_id", models.IntegerField(blank=True, null=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ids",
                        to="sleeper_bot.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rookie_year", models.CharField(max_length=250)),
                ("birth_date", models.DateField()),
                ("age", models.IntegerField()),
                ("height", models.CharField(max_length=250)),
                ("weight", models.CharField(max_length=250)),
                ("college", models.CharField(max_length=250)),
                ("high_school", models.CharField(max_length=250)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="sleeper_bot.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Practice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participation", models.CharField(max_length=250)),
                ("description", models.TextField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practices",
                        to="sleeper_bot.player",
                    ),
                ),
            ],
        ),
    ]
