# Generated by Django 5.0.8 on 2024-08-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleeper_bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="player_id",
            field=models.CharField(
                db_index=True,
                max_length=250,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
