# Generated by Django 5.0.8 on 2024-08-25 12:29

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleeper_bot", "0002_alter_player_player_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practice",
            name="player",
        ),
        migrations.AlterField(
            model_name="injury",
            name="body_part",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="injury",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="injury",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="injury",
            name="status",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="depth_chart_position",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="fantasy_positions",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("QB", "Quarterback"),
                    ("RB", "Running Back"),
                    ("WR", "Wide Receiver"),
                    ("TE", "Tight End"),
                    ("K", "Kicker"),
                    ("DEF", "Defense"),
                    ("DB", "Defensive Back"),
                    ("LB", "Linebacker"),
                    ("DL", "Defensive Line"),
                    ("OL", "Offensive Line"),
                    ("OG", "Offensive Guard"),
                    ("OT", "Offensive Tackle"),
                    ("LS", "Long Snapper"),
                    ("P", "Punter"),
                ],
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="search_rank",
            field=models.IntegerField(blank=True, default=9999999, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="status",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ARI", "Arizona"),
                    ("ATL", "Atlanta"),
                    ("BAL", "Baltimore"),
                    ("BUF", "Buffalo"),
                    ("CAR", "Carolina"),
                    ("CHI", "Chicago"),
                    ("CIN", "Cincinnati"),
                    ("CLE", "Cleveland"),
                    ("DAL", "Dallas"),
                    ("DEN", "Denver"),
                    ("DET", "Detroit"),
                    ("GB", "Green Bay"),
                    ("HOU", "Houston"),
                    ("IND", "Indianapolis"),
                    ("JAX", "Jacksonville"),
                    ("KC", "Kansas City"),
                    ("LV", "Las Vegas"),
                    ("LAR", "Los Angeles Rams"),
                    ("MIA", "Miami"),
                    ("MIN", "Minnesota"),
                    ("NE", "New England"),
                    ("NO", "New Orleans"),
                    ("NYG", "New York Giants"),
                    ("NYJ", "New York Jets"),
                    ("PHI", "Philadelphia"),
                    ("PIT", "Pittsburgh"),
                    ("SF", "San Francisco"),
                    ("SEA", "Seattle"),
                    ("TB", "Tampa Bay"),
                    ("TEN", "Tennessee"),
                    ("WAS", "Washington"),
                ],
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="playerids",
            name="channel_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="playermetadata",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playermetadata",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="playermetadata",
            name="college",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="playermetadata",
            name="height",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="playermetadata",
            name="high_school",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="playermetadata",
            name="rookie_year",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="playermetadata",
            name="weight",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name="Competition",
        ),
        migrations.DeleteModel(
            name="Practice",
        ),
    ]
