# Generated by Django 5.0.8 on 2024-08-25 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sleeper_bot", "0003_remove_practice_player_alter_injury_body_part_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playermetadata",
            name="rookie_year",
        ),
    ]
