# Generated by Django 5.0.8 on 2024-08-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sleeper_bot", "0005_remove_playerids_channel_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Injury",
        ),
    ]
